### ISSUE TITLE
[logstash.outputs.datadoglogs] TCP exception {:exception=>#<EOFError: End of file reached>

### ISSUE THREAD

**Issue by lifeofguenter** [DataDog/logstash-output-datadog_logs#11]
Every now and then I get the following error:

```
logstash_1_872cd354b170 | [2018-11-23T12:35:09,942][WARN ][logstash.outputs.datadoglogs] TCP exception {:exception=>#<EOFError: End of file reached>, :backtrace=>["org/jruby/ext/openssl/SSLSocket.java:857:in `sysread'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-datadog_logs-0.2.1/lib/logstash/outputs/datadog_logs.rb:33:in `block in register'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-codec-json-3.0.5/lib/logstash/codecs/json.rb:42:in `encode'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-datadog_logs-0.2.1/lib/logstash/outputs/datadog_logs.rb:54:in `receive'", "/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:89:in `block in multi_receive'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:89:in `multi_receive'", "org/logstash/config/ir/compiler/OutputStrategyExt.java:114:in `multi_receive'", "org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java:97:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:373:in `block in output_batch'", "org/jruby/RubyHash.java:1343:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:372:in `output_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:324:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:286:in `block in start_workers'"]}
```

It unfortunately completely crashes the processing for further logs of that type (rsyslog)

**Comment by le-he-hoo** [comment]
Thanks for reaching out!
Just to close the loop, this is now associated with a support ticket

**Comment by ajacquemot** [comment]
Hi @lifeofguenter,

Thanks for reporting this issue, we've just released a new version of the plugin containing few changes on how we manage the TCP socket, we rewrote the logic and I am confident that it will fix your issue according to https://github.com/elastic/logstash/issues/8524.
Thanks,

Alexandre
